import { useState } from 'react';
import { Check, ChevronDown, Heart, Link2, Maximize2, Pause, Play, Radio, Share2, Sparkles, Volume2, X } from 'lucide-react';
import './_group.css';

type Line = { time: number; text: string; note: string };
const lyrics: Line[] = [
  { time: 0, text: 'Lights down, breathe in', note: 'opening' }, { time: 12, text: 'We found a little fire in the quiet', note: 'verse 01' },
  { time: 27, text: 'Hands up, let the whole room know', note: 'pre-chorus' }, { time: 41, text: 'We are louder when we sing together', note: 'chorus' },
  { time: 57, text: 'Stay with me through the afterglow', note: 'chorus' }, { time: 75, text: 'Every heartbeat keeps the rhythm', note: 'verse 02' },
  { time: 91, text: 'Call my name, I will answer back', note: 'build' }, { time: 107, text: 'This is our night, our little orbit', note: 'bridge' },
  { time: 126, text: 'One more time, make the ceiling shake', note: 'final chorus' }, { time: 145, text: 'Hold the moment, do not let it fade', note: 'final chorus' },
  { time: 170, text: 'Lights up, we are still here', note: 'outro' }, { time: 194, text: 'See you at the next replay', note: 'outro' },
];
const chant = lyrics.map((line, i) => ({ ...line, text: ['— settle in', 'HEY! HEY!', 'Hands up! Hands up!', 'WE SING TOGETHER!', 'STAY! STAY! STAY!', 'Oh-oh-oh-oh', 'Your name! Your name!', 'THIS IS OUR NIGHT!', 'ONE MORE TIME!', 'WE ARE STILL HERE!', 'HEY! HEY! HEY!', 'See you next time'][i] }));
const time = (n: number) => `${Math.floor(n / 60)}:${String(Math.floor(n % 60)).padStart(2, '0')}`;

export function Current() {
  const [playing, setPlaying] = useState(false), [seconds, setSeconds] = useState(0), [mode, setMode] = useState<'lyrics' | 'fanchant'>('lyrics');
  const [liked, setLiked] = useState(false), [muted, setMuted] = useState(false), [modal, setModal] = useState(false), [copied, setCopied] = useState(false);
  const lines = mode === 'lyrics' ? lyrics : chant, active = lines.reduce((a, l, i) => l.time <= seconds ? i : a, 0), progress = seconds / 212 * 100;
  return <div className="video-lyrics-current">
    <header className="studio-topbar"><div className="brand-lockup"><div className="brand-mark">VL</div><span className="brand-name">Video Lyrics Studio</span><span className="brand-kicker">room 01</span></div><div className="topbar-status"><span className="status-dot" />session ready</div><div className="topbar-actions"><button className="share-button" onClick={() => { setCopied(true); setTimeout(() => setCopied(false), 1800); }}>{copied ? <Check size={14} /> : <Share2 size={14} />}{copied ? 'Copied' : 'Share room'}</button></div></header>
    <main className="app-main"><section className="room-heading"><div><div className="eyebrow">private concert room / fan practice mode</div><h1>Sing it like <em>you were there.</em></h1></div><p className="heading-note">A focused replay space for the lyric, the breath, and the exact moment the room sings back.</p></section>
      <section className="live-layout"><div><article className="stage-card"><div className="video-wrap"><div className="player-frame"><div className="video-placeholder"><div className="placeholder-lights"><span /><span /><span /><span /><span /></div></div></div><div className="video-overlay-label"><span className="video-signal"><Radio size={11} /></span>sample performance / demo sync</div></div>
        <div className="stage-controls"><div className="progress-track"><span className="timestamp">{time(seconds)}</span><input className="progress-range" type="range" min="0" max="212" value={seconds} onChange={e => setSeconds(Number(e.target.value))} /><span className="timestamp">3:32</span></div><div className="control-row"><div className="control-left"><button className="play-button" onClick={() => setPlaying(!playing)} aria-label="Play performance">{playing ? <Pause size={17} fill="currentColor" /> : <Play size={17} fill="currentColor" />}</button><div><div className="control-label">{playing ? 'Playing live' : 'Ready to replay'}</div><div className="control-meta">demo clock fallback</div></div></div><div className="control-right"><span className="control-meta">sample video</span><button className="icon-button" onClick={() => setMuted(!muted)} aria-label="Mute"><Volume2 size={15} style={{ opacity: muted ? .4 : 1 }} /></button><button className="icon-button" aria-label="Expand player"><Maximize2 size={15} /></button></div></div></div>
        <div className="song-meta"><div><h2 className="track-title">Night Bloom — live room take</h2><p className="track-artist">sample performance · sync demo by Video Lyrics Studio</p></div><div className="track-tags"><span className="tag tag-highlight">practice cut</span><span className="tag">3:32</span><button className="icon-button" onClick={() => setLiked(!liked)} aria-label="Save this room"><Heart size={15} fill={liked ? 'currentColor' : 'none'} /></button></div></div></article>
        <div className="under-grid"><div className="info-panel"><div className="info-copy"><div className="info-glyph"><Sparkles size={16} /></div><div><p className="info-title">Words follow the moment</p><p className="info-description">Tap any line to jump there. The room will keep your place.</p></div></div><div className="progress-caption">{Math.round(progress)}%<br />through the set</div></div><button className="info-panel change-button" onClick={() => setModal(true)}><div className="info-copy"><div className="info-glyph"><Link2 size={16} /></div><div><p className="info-title">Bring your own performance</p><p className="info-description">Swap the sample for a YouTube URL.</p></div></div><ChevronDown size={16} style={{ transform: 'rotate(-90deg)' }} /></button></div></div>
        <aside className="lyrics-card"><div className="lyrics-head"><div className="lyrics-headline"><div><div className="eyebrow">live transcript</div><h2 className="lyrics-title">{mode === 'lyrics' ? 'Follow the lyric' : 'Join the room'}</h2></div><div className="sync-status"><span className="live-dot" />demo sync</div></div><div className="mode-switch"><button className={`mode-button ${mode === 'lyrics' ? 'active' : ''}`} onClick={() => setMode('lyrics')}>Lyrics</button><button className={`mode-button ${mode === 'fanchant' ? 'active' : ''}`} onClick={() => setMode('fanchant')}>Fanchant</button></div></div><div className="lyric-scroll">{lines.map((line, i) => <button className={`lyric-line ${i === active ? 'active' : ''}`} key={line.time} onClick={() => setSeconds(line.time)}><span className="line-time">{time(line.time)}</span><span className="line-content"><span className="line-text">{line.text}</span><span className="line-note">{line.note}</span></span><span className="line-pulse" /></button>)}</div></aside>
      </section>
    </main>
    {modal && <div className="modal-backdrop"><form className="modal-card" onSubmit={e => { e.preventDefault(); setModal(false); }}><div className="modal-top"><div><div className="eyebrow">change the stage</div><h2 className="modal-title">Load a performance</h2></div><button className="icon-button" onClick={() => setModal(false)}><X size={16} /></button></div><p className="modal-copy">Use a YouTube watch link, short link, embed link, or video ID. Your room state stays in the URL for easy sharing.</p><label className="mono-label">youtube url</label><input className="url-input" defaultValue="https://www.youtube.com/watch?v=M7lc1UVf-VE" /><div className="modal-actions"><button className="secondary-action" onClick={() => setModal(false)}>Cancel</button><button className="primary-action">Load into room</button></div></form></div>}
    {copied && <div className="toast-note">Room link copied</div>}
  </div>;
}